---
- name: '{{ systemd_timer_name }} Timer | Create script file' 
  copy:
    dest: '{{ systemd_timer_script_path }}'
    content: '{{ systemd_timer_script_content }}'
    group: adm
    mode: 0750

- name: '{{ systemd_timer_name }} Timer | Create service file'
  template:
    src: 'main.service.j2'
    dest: '/lib/systemd/system/{{ systemd_timer_name }}.service'
    mode: 0644

- name: '{{ systemd_timer_name }} Timer | Create timer file'
  template:
    src: 'main.timer.j2'
    dest: '/lib/systemd/system/{{ systemd_timer_name }}.timer'
    mode: 0644

- name: '{{ systemd_timer_name }} Timer | Reload systemctl'
  command: systemctl daemon-reload

- name: '{{ systemd_timer_name }} Timer | (Re)start service'
  service:
    name: '{{ systemd_timer_name }}.service'
    state: started
    enabled: true

- name: '{{ systemd_timer_name }} Timer | Enable the timer'
  systemd:
    name: '{{ systemd_timer_name }}.timer'
    state: started
    enabled: yes
