---
- name: '{{ systemd_timer_name }} Timer | Create service file'
  template:
    src: 'main.service.j2'
    dest: '{{ systemd_timer_service_path }}/{{ systemd_timer_name }}.service'
    owner: '{{ systemd_timer_service_owner }}'
    group: '{{ systemd_timer_service_group }}'
    mode: 0640

- name: '{{ systemd_timer_name }} Timer | Create timer file'
  template:
    src: 'main.timer.j2'
    dest: '{{ systemd_timer_service_path }}/{{ systemd_timer_name }}.timer'
    owner: '{{ systemd_timer_service_owner }}'
    group: '{{ systemd_timer_service_group }}'
    mode: 0640

- name: '{{ systemd_timer_name }} Timer | Reload systemctl'
  command: systemctl daemon-reload

- name: '{{ systemd_timer_name }} Timer | (Re)start service'
  service:
    name: '{{ systemd_timer_name }}.service'
    state: '{{ systemd_timer_start_on_creation | ternary("started", "stopped") }}'
    enabled: true

- name: '{{ systemd_timer_name }} Timer | Enable the timer'
  systemd:
    name: '{{ systemd_timer_name }}.timer'
    state: '{{ systemd_timer_enabled | ternary("started", "stopped") }}'
    enabled: '{{ systemd_timer_enabled }}'
